@startuml

title Classes 

interface Talkable{
    +talk(): String
}

abstract class Animal implements Talkable{
    # nome: String
    + Animal(name: String)
    + getNome(): String
    + talk(): String
}

class Cat extends Animal{
    + Gato(name: String)
    + talk(): String
}

class Dog extends Animal{
    + Dog(name: String)
    + talk(): String
}

class Radio implements Talkable{
    + Radio()
    + talk(): String
}

class FarmApp{
    + main(args: String[]): void
}

' Relacionamentos
Animal <|-- Dog
Animal <|-- Cat
Talkable <|.. Animal
Talkable <|.. Radio
FarmApp --> Talkable : usa

@enduml
